name: de_comp_core
description: "A core functionality for DeComp"
version: 0.0.2
homepage: https://github.com/karroze/de_comp_core

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  meta: ^1.15.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
